#!/usr/bin/env bash
# run-tests.sh — smoke tests for ssot-lint.sh
#
# Design: no fixture files left on disk. Each scenario builds a minimal SSOT
#         project under mktemp, then asserts on key output and exit codes.
#         Self-contained, easy to read. Covers v2.13 checks 6/7/8/9, the
#         v2.17 handwritten vs SSOT-generated adapter boundary, v2.19
#         product skeleton, v2.31 decision lifecycle fields, v2.34 ledger
#         WARN heuristics, v2.35 actionability WARN heuristics, v2.36 KISS
#         table-density WARN heuristics, v2.47 intent/truth narrative WARN,
#         v2.52 open-risk / temporary-surface checks, v2.53 non-silent
#         deferral checks, and the clean baseline.
#
# Usage:       bash assets/scripts/test/run-tests.sh
# Exit codes:  0 all pass; 1 some failed.
set -uo pipefail

LINT="$(cd "$(dirname "$0")/.." && pwd)/ssot-lint.sh"
DOCTOR_SKILL="$(cd "$(dirname "$0")/../../.." && pwd)"
SKILLS_DIR="$(cd "$DOCTOR_SKILL/.." && pwd)"
PASS=0
FAIL=0

# Same hash impl as ssot-lint.sh ssot_hash (test env assumes sha256sum).
thash() { sha256sum "$1" | cut -c1-12; }

assert_contains() { # desc out needle
  if printf '%s' "$2" | grep -qF "$3"; then echo "  ok   : $1"; PASS=$((PASS + 1));
  else echo "  FAIL : $1 (output missing: $3)"; FAIL=$((FAIL + 1)); fi
}
assert_not_contains() { # desc out needle
  if printf '%s' "$2" | grep -qF "$3"; then echo "  FAIL : $1 (output should not contain: $3)"; FAIL=$((FAIL + 1));
  else echo "  ok   : $1"; PASS=$((PASS + 1)); fi
}
assert_exit() { # desc actual expected
  if [[ "$2" == "$3" ]]; then echo "  ok   : $1"; PASS=$((PASS + 1));
  else echo "  FAIL : $1 (exit code $2 != $3)"; FAIL=$((FAIL + 1)); fi
}
assert_file() { # desc path
  if [[ -f "$2" ]]; then echo "  ok   : $1"; PASS=$((PASS + 1));
  else echo "  FAIL : $1 (missing file: $2)"; FAIL=$((FAIL + 1)); fi
}

make_base() { # $1=root — build a clean, all-PASS minimal SSOT project (git repo).
              # Fixture content is intentionally Chinese to exercise
              # documentation_language: 中文 semantics; do not translate.
  local r="$1"
  mkdir -p "$r/SSOT/product/capabilities" "$r/SSOT/product/journeys" "$r/SSOT/architecture" "$r/SSOT/gotchas" "$r/src"
  printf '# SSOT 导航\n\n```\n├── product/\n├── architecture/\n└── gotchas/\n```\n\n- [product](product/README.md)\n- [architecture](architecture/README.md)\n\n## Easily confused with\n\n（待补充）\n\n## Out of scope\n\n（待补充）\n' > "$r/SSOT/README.md"
  printf -- '---\nintent_recovery: gap\n---\n# 产品\n\n```\n├── capabilities/\n├── journeys/\n├── prd.md\n├── product-model.md\n└── roadmap-and-acceptance.md\n```\n\n- [PRD](prd.md)\n- [Product model](product-model.md)\n- [Roadmap](roadmap-and-acceptance.md)\n\n## Easily confused with\n\n（待补充）\n\n## Out of scope\n\n（待补充）\n' > "$r/SSOT/product/README.md"
  printf -- '---\nintent_recovery: gap\n---\n# PRD Spine\n' > "$r/SSOT/product/prd.md"
  printf -- '---\nintent_recovery: gap\n---\n# Product Model\n' > "$r/SSOT/product/product-model.md"
  printf -- '---\nintent_recovery: gap\n---\n# Roadmap And Acceptance\n' > "$r/SSOT/product/roadmap-and-acceptance.md"
  printf -- '---\nintent_recovery: gap\n---\n# Product Capabilities\n' > "$r/SSOT/product/capabilities/README.md"
  printf -- '---\nintent_recovery: gap\n---\n# Product Journeys\n' > "$r/SSOT/product/journeys/README.md"
  printf -- '---\nintent_recovery: gap\n---\n# 架构\n\n核心不变量：请求必须经过鉴权。\n\n## Easily confused with\n\n（待补充）\n\n## Out of scope\n\n（待补充）\n' > "$r/SSOT/architecture/README.md"
  printf '# 陷阱索引\n\n- [0001](0001-x.md)\n\n## Easily confused with\n\n（待补充）\n\n## Out of scope\n\n（待补充）\n' > "$r/SSOT/gotchas/README.md"
  printf -- '---\nconfidence: candidate\nsource: code-analysis\ndiscovered_at: 2026-05-29\nevidence: "src/foo.ts#barFunc"\n---\n# 陷阱 X\n' > "$r/SSOT/gotchas/0001-x.md"
  printf 'export function barFunc() { return 1 }\n' > "$r/src/foo.ts"
  printf '| tracked_commit | `PLACEHOLDER` |\n| tracked_session | `2026-06-08T00:00:00Z` |\n| tracked_skill_version | `2.19` |\n| documentation_language | 中文 |\n| documentation_language_evidence | README |\n| coverage_result | in_progress |\n\n| 区域 | 状态 | 备注 |\n|---|---|---|\n| product | gap | |\n| architecture | gap | |\n' > "$r/SSOT/STATUS.md"
  git -C "$r" init -q
  git -C "$r" add -A >/dev/null 2>&1
  git -C "$r" -c user.email=t@t.t -c user.name=t commit -qm init >/dev/null 2>&1
  local head
  head=$(git -C "$r" rev-parse HEAD)
  sed -i "s/PLACEHOLDER/$head/" "$r/SSOT/STATUS.md"
}

add_clean_adapter() { # $1=root — thin adapter with marker + correct source hash + SSOT routing.
  local r="$1" ha
  ha=$(thash "$r/SSOT/architecture/README.md")
  {
    printf '<!-- SSOT-generated | generated_at: 2026-05-29 -->\n'
    printf '<!-- SSOT-source: SSOT/architecture/README.md@%s -->\n' "$ha"
    printf '<!-- generated by SSOT -->\n\n'
    printf '# proj\n\n开始任何任务前先读 SSOT/STATUS.md。\n'
  } > "$r/AGENTS.md"
}

run() { bash "$LINT" "$1/SSOT" 2>&1; }

set_protocol_238() { # $1=root — opt the temp fixture into v2.38 checks.
  sed -i 's/| tracked_skill_version | `2.19` |/| tracked_skill_version | `2.38` |/' "$1/SSOT/STATUS.md"
}

resolve_template_placeholders() { # $1=root — replace skeleton residue in fixture prose before marking areas covered.
  find "$1/SSOT" -name '*.md' -type f -print0 | xargs -0 sed -i 's/（待补充）/无/g'
}

echo "== S0 bundle package shape (each skill has SKILL.md + agents/openai.yaml) =="
for skill in ssot-preflight ssot-bootstrap ssot-closeout ssot-audit ssot-doctor ssot-skill; do
  assert_file "$skill has SKILL.md" "$SKILLS_DIR/$skill/SKILL.md"
  assert_file "$skill has agents/openai.yaml" "$SKILLS_DIR/$skill/agents/openai.yaml"
done
for template in product-readme.md product-prd.md product-model.md product-roadmap-and-acceptance.md product-capabilities-readme.md product-journeys-readme.md product-capability-entry.md product-journey-entry.md; do
  # Bilingual split: canonical templates live under en/ and zh/.
  assert_file "template en/$template exists" "$SKILLS_DIR/ssot-bootstrap/assets/templates/en/$template"
  assert_file "template zh/$template exists" "$SKILLS_DIR/ssot-bootstrap/assets/templates/zh/$template"
done

echo "== S1 clean (all PASS, exit 0) =="
T=$(mktemp -d); make_base "$T"; add_clean_adapter "$T"
out=$(run "$T"); code=$?
assert_exit "clean exits 0" "$code" "0"
assert_not_contains "clean has no FAIL" "$out" "[FAIL]"
assert_not_contains "clean has no WARN" "$out" "[WARN]"
rm -rf "$T"

echo "== S2 architecture body contains hypothesis (check 6 -> FAIL) =="
T=$(mktemp -d); make_base "$T"
printf '\nconfidence: hypothesis\n' >> "$T/SSOT/architecture/README.md"
out=$(run "$T"); code=$?
assert_contains "hypothesis triggers FAIL" "$out" "confidence: hypothesis"
assert_exit "hypothesis exits 2" "$code" "2"
rm -rf "$T"

echo "== S3 handwritten AGENTS with SSOT routing (no ADAPTER WARN) =="
T=$(mktemp -d); make_base "$T"
printf '# 手写 AGENTS\n\n实质性任务开始前使用 $ssot-preflight，并按 SSOT/README.md 路由。\n' > "$T/AGENTS.md"
out=$(run "$T"); code=$?
assert_exit "handwritten routed file exits 0" "$code" "0"
assert_not_contains "handwritten routed file: no ADAPTER" "$out" "[ADAPTER]"
assert_not_contains "handwritten routed file: no WARN" "$out" "[WARN]"
rm -rf "$T"

echo "== S4 handwritten AGENTS without SSOT routing (check 9 -> CONSUMPTION) =="
T=$(mktemp -d); make_base "$T"
printf '# 手写 AGENTS\n\n这里只有仓库命令，没有长期记忆入口。\n' > "$T/AGENTS.md"
out=$(run "$T"); code=$?
assert_contains "handwritten unrouted triggers CONSUMPTION" "$out" "[CONSUMPTION]"
assert_exit "handwritten unrouted exits 1" "$code" "1"
assert_not_contains "handwritten unrouted: no ADAPTER" "$out" "[ADAPTER]"
rm -rf "$T"

echo "== S5 SSOT-generated adapter: source hash drift (check 7 -> WARN) =="
T=$(mktemp -d); make_base "$T"; add_clean_adapter "$T"
printf '\n额外改动导致源 hash 变化。\n' >> "$T/SSOT/architecture/README.md"
out=$(run "$T"); code=$?
assert_contains "source drift triggers WARN" "$out" "source file changed"
rm -rf "$T"

echo "== S6 SSOT-generated adapter: too long (check 7 -> WARN) =="
T=$(mktemp -d); make_base "$T"; add_clean_adapter "$T"
for i in $(seq 1 55); do printf 'extra line %s\n' "$i" >> "$T/AGENTS.md"; done
out=$(run "$T"); code=$?
assert_contains "over-length triggers WARN" "$out" "exceeds 50 lines"
rm -rf "$T"

echo "== S7 evidence symbol stale (check 8 -> STALE) =="
T=$(mktemp -d); make_base "$T"
sed -i 's/#barFunc/#ghostFunc/' "$T/SSOT/gotchas/0001-x.md"
out=$(run "$T"); code=$?
assert_contains "missing symbol triggers STALE" "$out" "[STALE] evidence symbol not found"
rm -rf "$T"

echo "== S8 SSOT-generated adapter without SSOT routing (check 9 -> CONSUMPTION) =="
T=$(mktemp -d); make_base "$T"
{
  printf '<!-- SSOT-generated | generated_at: 2026-05-29 -->\n'
  printf '# proj\n\n这里没有指向长期记忆目录的指令。\n'
} > "$T/AGENTS.md"
out=$(run "$T"); code=$?
assert_contains "no SSOT routing triggers CONSUMPTION" "$out" "[CONSUMPTION]"
rm -rf "$T"

echo "== S9 product skeleton missing (check 10 -> PRODUCT FAIL) =="
T=$(mktemp -d); make_base "$T"
rm -rf "$T/SSOT/product/journeys"
out=$(run "$T"); code=$?
assert_contains "missing product skeleton triggers PRODUCT" "$out" "[PRODUCT]"
assert_exit "missing product skeleton exits 2" "$code" "2"
rm -rf "$T"

echo "== S10 STATUS missing product row (check 1 -> FAIL) =="
T=$(mktemp -d); make_base "$T"
sed -i '/| product |/d' "$T/SSOT/STATUS.md"
out=$(run "$T"); code=$?
assert_contains "missing product row triggers FAIL" "$out" "missing required product row"
assert_exit "missing product row exits 2" "$code" "2"
rm -rf "$T"

echo "== S11 decisions entry missing lifecycle fields (check 11 -> DECISION FAIL) =="
T=$(mktemp -d); make_base "$T"; add_clean_adapter "$T"
mkdir -p "$T/SSOT/decisions"
printf '# Decisions\n' > "$T/SSOT/decisions/README.md"
# Decision entry with only status; missing implementation_state/created_on/introduced_in.
{
  printf -- '---\nstatus: accepted\n---\n# 0001 Example\n'
} > "$T/SSOT/decisions/0001-example.md"
out=$(run "$T"); code=$?
assert_contains "missing implementation_state triggers DECISION" "$out" "[DECISION]"
assert_contains "missing created_on flagged" "$out" "missing required field 'created_on'"
assert_contains "missing introduced_in flagged" "$out" "missing required field 'introduced_in'"
assert_exit "missing decision fields exits 2" "$code" "2"
rm -rf "$T"

echo "== S12 decisions entry with all required fields (check 11 -> PASS) =="
T=$(mktemp -d); make_base "$T"; add_clean_adapter "$T"
mkdir -p "$T/SSOT/decisions"
printf '# Decisions\n\n## Easily confused with\n\n（待补充）\n\n## Out of scope\n\n（待补充）\n' > "$T/SSOT/decisions/README.md"
{
  printf -- '---\nstatus: accepted\nimplementation_state: pending\ncreated_on: 2026-06-12\nupdated_on: 2026-06-12\nintroduced_in: abcdef1\nclosure_condition: "implementation_state becomes implemented or decision is superseded"\nrevisit_signal: "path-glob:src/**"\n---\n# 0001 Example\n'
} > "$T/SSOT/decisions/0001-example.md"
out=$(run "$T"); code=$?
assert_not_contains "complete decision entry has no DECISION FAIL" "$out" "[DECISION]"
assert_exit "complete decision entry exits 0" "$code" "0"
rm -rf "$T"

echo "== S13 bootstrap-archaeology archive is exempt (check 11) =="
T=$(mktemp -d); make_base "$T"; add_clean_adapter "$T"
mkdir -p "$T/SSOT/decisions"
printf '# Decisions\n\n## Easily confused with\n\n（待补充）\n\n## Out of scope\n\n（待补充）\n' > "$T/SSOT/decisions/README.md"
{
  printf -- '---\nid: DEC-0000\ntype: bootstrap-archaeology\nstatus: archived\narchived_at: 2026-06-12\n---\n# 0000 Bootstrap Recon\n'
} > "$T/SSOT/decisions/0000-bootstrap-recon.md"
out=$(run "$T"); code=$?
assert_not_contains "archaeology archive exempt from DECISION check" "$out" "[DECISION]"
assert_exit "archaeology-only decisions area exits 0" "$code" "0"
rm -rf "$T"

echo "== S14 STATUS Notes ledger warning (check 5 -> STATUS-NOTES-LEDGER WARN) =="
T=$(mktemp -d); make_base "$T"; add_clean_adapter "$T"
resolve_template_placeholders "$T"
sed -i 's/| product | gap | |/| product | covered | 2026-06-13 BUG-0001 批次验证 passed |/' "$T/SSOT/STATUS.md"
out=$(run "$T"); code=$?
assert_contains "STATUS notes ledger triggers WARN tag" "$out" "[STATUS-NOTES-LEDGER]"
assert_exit "STATUS notes ledger exits 1" "$code" "1"
rm -rf "$T"

echo "== S15 README derived-state warning (check 5b -> INDEX-DERIVED-STATE WARN) =="
T=$(mktemp -d); make_base "$T"; add_clean_adapter "$T"
printf '\n本仓库目前索引 12 条 bug，其中 10 条 fixed、2 条 active。\n' >> "$T/SSOT/product/README.md"
out=$(run "$T"); code=$?
assert_contains "README derived state triggers WARN tag" "$out" "[INDEX-DERIVED-STATE]"
assert_exit "README derived state exits 1" "$code" "1"
rm -rf "$T"

echo "== S16 non-owner shadow ledger warning (check 5c -> SHADOW-LEDGER WARN) =="
T=$(mktemp -d); make_base "$T"; add_clean_adapter "$T"
mkdir -p "$T/SSOT/development"
printf '# Audit Playbook\n\n## 验证说明\n\n2026-06-13 smoke passed。\n' > "$T/SSOT/development/audit-playbook.md"
out=$(run "$T"); code=$?
assert_contains "shadow ledger triggers WARN tag" "$out" "[SHADOW-LEDGER]"
assert_exit "shadow ledger exits 1" "$code" "1"
rm -rf "$T"

echo "== S17 STATUS last_stop_review ledger warning (check 5d -> STATUS-STOP-REVIEW-LEDGER WARN) =="
T=$(mktemp -d); make_base "$T"; add_clean_adapter "$T"
printf '\n| last_stop_review | pytest passed, Playwright screenshot archived, Browser DOM verification command output copied into STATUS |\n' >> "$T/SSOT/STATUS.md"
out=$(run "$T"); code=$?
assert_contains "STATUS stop-review ledger triggers WARN tag" "$out" "[STATUS-STOP-REVIEW-LEDGER]"
assert_exit "STATUS stop-review ledger exits 1" "$code" "1"
rm -rf "$T"

echo "== S18 fixed major bug entry missing quick entry warning (check 5e -> ENTRY-ACTIONABILITY WARN) =="
T=$(mktemp -d); make_base "$T"; add_clean_adapter "$T"
mkdir -p "$T/SSOT/bugs"
printf '# Bugs\n' > "$T/SSOT/bugs/README.md"
printf -- '---\nstatus: fixed\nseverity: major\n---\n# Runtime output missing\n\n## Root cause\n\nThe event was not projected.\n' > "$T/SSOT/bugs/0001-runtime-output.md"
out=$(run "$T"); code=$?
assert_contains "bug missing quick entry triggers WARN tag" "$out" "[ENTRY-ACTIONABILITY]"
assert_exit "bug missing quick entry exits 1" "$code" "1"
rm -rf "$T"

echo "== S19 stop-review section ledger warning (check 5d -> STATUS-STOP-REVIEW-LEDGER WARN) =="
T=$(mktemp -d); make_base "$T"; add_clean_adapter "$T"
printf '\n## 停止审查闸门\n\n| scope | result | evidence |\n|---|---|---|\n| protocol | passed | pytest command output copied here, Playwright screenshot copied here, full verification transcript copied here |\n' >> "$T/SSOT/STATUS.md"
out=$(run "$T"); code=$?
assert_contains "stop-review section ledger triggers WARN tag" "$out" "[STATUS-STOP-REVIEW-LEDGER]"
assert_exit "stop-review section ledger exits 1" "$code" "1"
rm -rf "$T"

echo "== S20 overlong markdown line warning (check 5f -> READABILITY-LONG-LINE WARN) =="
T=$(mktemp -d); make_base "$T"; add_clean_adapter "$T"
printf '\n' >> "$T/SSOT/product/prd.md"
for _ in $(seq 1 950); do printf 'x' >> "$T/SSOT/product/prd.md"; done
printf '\n' >> "$T/SSOT/product/prd.md"
out=$(run "$T"); code=$?
assert_contains "overlong line triggers WARN tag" "$out" "[READABILITY-LONG-LINE]"
assert_exit "overlong line exits 1" "$code" "1"
rm -rf "$T"

echo "== S21 table-density warning (check 5g -> KISS-TABLE-DENSITY WARN) =="
T=$(mktemp -d); make_base "$T"; add_clean_adapter "$T"
{
  printf -- '---\nintent_recovery: gap\n---\n'
  printf '# 表格化文档\n\n这份文档只有一句开场，然后用表格承载全部内容。\n\n'
  printf '| a | b | c |\n|---|---|---|\n'
  for i in $(seq 1 75); do printf '| row-%s | value | value |\n' "$i"; done
} > "$T/SSOT/architecture/README.md"
out=$(run "$T"); code=$?
assert_contains "table density triggers KISS WARN tag" "$out" "[KISS-TABLE-DENSITY]"
assert_exit "table density exits 1" "$code" "1"
rm -rf "$T"

echo "== S22 v2.38 missing source inventory (check 5h -> SOURCE-INVENTORY FAIL) =="
T=$(mktemp -d); make_base "$T"; set_protocol_238 "$T"
mkdir -p "$T/docs"
printf '# Working Note\n\nCurrent runtime API notes without inventory.\n' > "$T/docs/work-note.md"
out=$(run "$T"); code=$?
assert_contains "missing source inventory triggers FAIL tag" "$out" "[SOURCE-INVENTORY]"
assert_exit "missing source inventory exits 2" "$code" "2"
rm -rf "$T"

echo "== S22b covered architecture manifest without intent/truth narrative (check 5g2 -> INTENT-TRUTH-NARRATIVE WARN) =="
T=$(mktemp -d); make_base "$T"
sed -i 's/| architecture | gap | |/| architecture | covered | |/' "$T/SSOT/STATUS.md"
{
  printf -- '---\nintent_recovery: gap\n---\n'
  printf '# 架构\n\n'
  printf '## 设计简报\n\n这里是一句开场。\n\n'
  printf '本文档的核心恢复清单见 _manifest.md。\n'
} > "$T/SSOT/architecture/README.md"
add_clean_adapter "$T"
out=$(run "$T"); code=$?
assert_contains "missing intent/truth narrative triggers WARN tag" "$out" "[INTENT-TRUTH-NARRATIVE]"
assert_exit "missing intent/truth narrative exits 1" "$code" "1"
rm -rf "$T"

echo "== S22c covered architecture manifest with intent/truth narrative (check 5g2 -> PASS) =="
T=$(mktemp -d); make_base "$T"
sed -i 's/| architecture | gap | |/| architecture | covered | |/' "$T/SSOT/STATUS.md"
{
  printf -- '---\nintent_recovery: gap\n---\n'
  printf '# 架构\n\n'
  printf '## 设计简报\n\n这里是一句开场。\n\n'
  printf '## 设计意图与设计真相\n\n当前 runtime-owner 拆分解释了设计意图和设计真相。\n\n'
  printf '本文档的核心恢复清单见 _manifest.md。\n\n'
  printf '## Easily confused with\n\n无易混淆 owner。\n\n## Out of scope\n\n无。\n'
} > "$T/SSOT/architecture/README.md"
add_clean_adapter "$T"
out=$(run "$T"); code=$?
assert_not_contains "present intent/truth narrative has no WARN tag" "$out" "[INTENT-TRUTH-NARRATIVE]"
assert_exit "present intent/truth narrative exits 0" "$code" "0"
rm -rf "$T"

echo "== S22d product README narrative covers PRD manifest (check 5g2 -> PASS) =="
T=$(mktemp -d); make_base "$T"
resolve_template_placeholders "$T"
add_clean_adapter "$T"
sed -i 's/| product | gap | |/| product | covered | |/' "$T/SSOT/STATUS.md"
printf '\n## 产品意图与产品真相\n\n产品入口先解释用户、问题、承诺和当前真相。\n' >> "$T/SSOT/product/README.md"
{
  printf -- '---\nintent_recovery: gap\n---\n'
  printf '# PRD Spine\n\n'
  printf '本文档的核心恢复清单见 _manifest.md。\n'
} > "$T/SSOT/product/prd.md"
out=$(run "$T"); code=$?
assert_not_contains "product README narrative covers PRD manifest" "$out" "[INTENT-TRUTH-NARRATIVE]"
assert_exit "product README narrative exits 0" "$code" "0"
rm -rf "$T"

echo "== S23 v2.38 complete working-doc lifecycle header (check 5h -> PASS) =="
T=$(mktemp -d); make_base "$T"; set_protocol_238 "$T"
mkdir -p "$T/docs"
cat > "$T/docs/poc-plan.md" <<'EOF'
<!--
lifecycle: working/poc
authority: downgraded
owner: SSOT/architecture/sdk-agent-runtime/README.md
absorbed_to: SSOT/architecture/sdk-agent-runtime/README.md
do_not_use_for: current runtime/API authority
review_on: 2026-06-16
-->
# PoC Plan

Current runtime API notes are exploratory; use the SSOT owner for authority.
EOF
out=$(run "$T"); code=$?
assert_not_contains "complete lifecycle header has no SOURCE-INVENTORY FAIL" "$out" "[SOURCE-INVENTORY]"
assert_not_contains "complete lifecycle header has no SOURCE-LIFECYCLE FAIL" "$out" "[SOURCE-LIFECYCLE]"
assert_exit "complete lifecycle header exits 0" "$code" "0"
rm -rf "$T"

echo "== S24 v2.38 strong facts without downgrade fields (check 5h -> SOURCE-LIFECYCLE FAIL) =="
T=$(mktemp -d); make_base "$T"; set_protocol_238 "$T"
mkdir -p "$T/docs"
printf '# Draft\n\nCurrent SDK runtime schema details.\n' > "$T/docs/draft.md"
printf '\n| Draft | docs/draft.md | lifecycle=working/draft | absorb | authority=downgraded | owner=SSOT/architecture/README.md | | review_on=2026-06-16 |\n' >> "$T/SSOT/STATUS.md"
out=$(run "$T"); code=$?
assert_contains "strong facts without downgrade triggers SOURCE-LIFECYCLE" "$out" "[SOURCE-LIFECYCLE]"
assert_exit "strong facts without downgrade exits 2" "$code" "2"
rm -rf "$T"

echo "== S25 v2.38 public thin doc without owner (check 5h -> THIN-DOCS FAIL) =="
T=$(mktemp -d); make_base "$T"; set_protocol_238 "$T"
mkdir -p "$T/docs"
cat > "$T/docs/public.md" <<'EOF'
<!--
lifecycle: public/thin-entry
authority: current
absorbed_to: SSOT/product/README.md
review_on: 2026-06-16
-->
# Public Entry
EOF
out=$(run "$T"); code=$?
assert_contains "public thin without owner triggers THIN-DOCS" "$out" "[THIN-DOCS]"
assert_exit "public thin without owner exits 2" "$code" "2"
rm -rf "$T"

echo "== S26 v2.38 audited exclusion missing owner (check 5h -> SOURCE-EXCLUSION FAIL) =="
T=$(mktemp -d); make_base "$T"; set_protocol_238 "$T"
printf '\n| Generated docs | pattern=docs/generated/* reason=generated last_checked=2026-06-16 review_trigger=generator-change |\n' >> "$T/SSOT/STATUS.md"
out=$(run "$T"); code=$?
assert_contains "audited exclusion missing owner triggers SOURCE-EXCLUSION" "$out" "[SOURCE-EXCLUSION]"
assert_exit "audited exclusion missing owner exits 2" "$code" "2"
rm -rf "$T"

echo "== S27 product owns implementation detail warning (check 5i -> PRODUCT-ARCH-DRIFT WARN) =="
T=$(mktemp -d); make_base "$T"; add_clean_adapter "$T"
mkdir -p "$T/SSOT/product/capabilities"
printf -- '---\nintent_recovery: gap\n---\n# Capability\n\n## API Reference\n\nRuntime endpoint details belong in architecture.\n' > "$T/SSOT/product/capabilities/01-bad.md"
out=$(run "$T"); code=$?
assert_contains "product implementation heading triggers PRODUCT-ARCH-DRIFT" "$out" "[PRODUCT-ARCH-DRIFT]"
assert_exit "product implementation heading exits 1" "$code" "1"
rm -rf "$T"

echo "== S28 checklist-heavy architecture warning (check 5i -> ARCH-CHECKLIST-HEAVY WARN) =="
T=$(mktemp -d); make_base "$T"; add_clean_adapter "$T"
mkdir -p "$T/SSOT/architecture/01-foo"
{
  printf -- '---\nintent_recovery: gap\n---\n'
  printf '# Foo\n\n'
  for i in $(seq 1 19); do printf '## Section %s\n\n<placeholder-%s>\n\n' "$i" "$i"; done
} > "$T/SSOT/architecture/01-foo/README.md"
out=$(run "$T"); code=$?
assert_contains "checklist-heavy architecture triggers ARCH-CHECKLIST-HEAVY" "$out" "[ARCH-CHECKLIST-HEAVY]"
assert_exit "checklist-heavy architecture exits 1" "$code" "1"
rm -rf "$T"

echo "== S29 unclosed markdown fence (check 23 -> MARKDOWN-FENCE FAIL) =="
T=$(mktemp -d); make_base "$T"; add_clean_adapter "$T"
printf '\n```text\nunterminated\n' >> "$T/SSOT/product/prd.md"
out=$(run "$T"); code=$?
assert_contains "unclosed fence triggers MARKDOWN-FENCE" "$out" "[MARKDOWN-FENCE]"
assert_exit "unclosed fence exits 2" "$code" "2"
rm -rf "$T"

echo "== S30 partial ADR missing closure fields (check 24 -> ADR-CLOSURE FAIL) =="
T=$(mktemp -d); make_base "$T"; add_clean_adapter "$T"
mkdir -p "$T/SSOT/decisions"
printf '# Decisions\n' > "$T/SSOT/decisions/README.md"
{
  printf -- '---\nstatus: accepted\nimplementation_state: partial\ncreated_on: 2026-06-30\nupdated_on: 2026-06-30\nintroduced_in: abcdef1\n---\n# 0001 Partial\n'
} > "$T/SSOT/decisions/0001-partial.md"
out=$(run "$T"); code=$?
assert_contains "partial ADR missing closure triggers ADR-CLOSURE" "$out" "[ADR-CLOSURE]"
assert_exit "partial ADR missing closure exits 2" "$code" "2"
rm -rf "$T"

echo "== S31 active debt missing closure fields (check 24 -> DEBT-CLOSURE FAIL) =="
T=$(mktemp -d); make_base "$T"; add_clean_adapter "$T"
mkdir -p "$T/SSOT/tech-debt"
printf '# Tech debt\n' > "$T/SSOT/tech-debt/README.md"
printf -- '---\nid: DEBT-0001\nstatus: active\npriority: high\n---\n# Active debt\n' > "$T/SSOT/tech-debt/0001-active.md"
out=$(run "$T"); code=$?
assert_contains "active debt missing closure triggers DEBT-CLOSURE" "$out" "[DEBT-CLOSURE]"
assert_exit "active debt missing closure exits 2" "$code" "2"
rm -rf "$T"

echo "== S32 temporary debt missing owner/reason/guard (check 24 -> TEMP-SURFACE FAIL) =="
T=$(mktemp -d); make_base "$T"; add_clean_adapter "$T"
mkdir -p "$T/SSOT/tech-debt"
printf '# Tech debt\n' > "$T/SSOT/tech-debt/README.md"
{
  printf -- '---\nid: DEBT-0002\nstatus: active\npriority: medium\ntemporary_surface: true\nclosure_condition: "grep -nR TODO src returns no match"\nrevisit_signal: "path-glob:src/**"\n---\n# Temporary surface\n'
} > "$T/SSOT/tech-debt/0002-temp.md"
out=$(run "$T"); code=$?
assert_contains "temporary debt missing guard fields triggers TEMP-SURFACE" "$out" "[TEMP-SURFACE]"
assert_exit "temporary debt missing guard fields exits 2" "$code" "2"
rm -rf "$T"

echo "== S33 covered area with placeholder residue (check 25 -> COVERED-PLACEHOLDER FAIL) =="
T=$(mktemp -d); make_base "$T"; add_clean_adapter "$T"
printf '\nTODO: replace this starter section.\n' >> "$T/SSOT/product/README.md"
sed -i 's/| product | gap | |/| product | covered | |/' "$T/SSOT/STATUS.md"
out=$(run "$T"); code=$?
assert_contains "covered placeholder triggers COVERED-PLACEHOLDER" "$out" "[COVERED-PLACEHOLDER]"
assert_exit "covered placeholder exits 2" "$code" "2"
rm -rf "$T"

echo "== S34 STATUS only/no remaining contradicts open gaps (check 26 -> STATUS-AGGREGATE FAIL) =="
T=$(mktemp -d); make_base "$T"; add_clean_adapter "$T"
printf '\n| last_stop_review | remaining=existing non-blocking gaps only (DEBT-0009) |\n\n## Open Gaps\n\n| Area | Status | Gap description | Blocking level |\n|---|---|---|---|\n| testing | gap | Browser smoke missing | non-blocking |\n| release | gap | Release automation missing | non-blocking |\n' >> "$T/SSOT/STATUS.md"
out=$(run "$T"); code=$?
assert_contains "contradictory remaining summary triggers STATUS-AGGREGATE" "$out" "[STATUS-AGGREGATE]"
assert_exit "contradictory remaining summary exits 2" "$code" "2"
rm -rf "$T"

echo "== S35 open gap with待立 debt and no owner (check 27 -> GAP-OWNER FAIL) =="
T=$(mktemp -d); make_base "$T"; add_clean_adapter "$T"
printf '\n## Open Gaps\n\n| Area | Status | Gap description | Blocking level |\n|---|---|---|---|\n| testing | gap | frontend lint CI 待立 tech-debt | non-blocking |\n' >> "$T/SSOT/STATUS.md"
out=$(run "$T"); code=$?
assert_contains "unowned gap triggers GAP-OWNER" "$out" "[GAP-OWNER]"
assert_exit "unowned gap exits 2" "$code" "2"
rm -rf "$T"

echo "== S36 STATUS resolved capture with pending action (check 28 -> CAPTURE-LIFECYCLE FAIL) =="
T=$(mktemp -d); make_base "$T"; add_clean_adapter "$T"
printf '\n### Pending Captures (cycle passed)\n\nCycle passed. Pending action: add this later during the next audit batch.\n' >> "$T/SSOT/STATUS.md"
out=$(run "$T"); code=$?
assert_contains "pending action in capture triggers CAPTURE-LIFECYCLE" "$out" "[CAPTURE-LIFECYCLE]"
assert_exit "pending action in capture exits 2" "$code" "2"
rm -rf "$T"

echo "== S37 open gap with vague later wording and no owner (check 29 -> SILENT-DEFERRAL FAIL) =="
T=$(mktemp -d); make_base "$T"; add_clean_adapter "$T"
printf '\n## Open Gaps\n\n| Area | Status | Gap description | Blocking level |\n|---|---|---|---|\n| testing | gap | Handle frontend lint later when convenient | non-blocking |\n' >> "$T/SSOT/STATUS.md"
out=$(run "$T"); code=$?
assert_contains "silent deferral triggers SILENT-DEFERRAL" "$out" "[SILENT-DEFERRAL]"
assert_exit "silent deferral exits 2" "$code" "2"
rm -rf "$T"

echo "== S38 owner-backed deferral with revisit signal passes check 29 =="
T=$(mktemp -d); make_base "$T"; add_clean_adapter "$T"
mkdir -p "$T/SSOT/tech-debt"
printf '# Tech debt\n\n## Easily confused with\n\nnone\n\n## Out of scope\n\nnone -- covers complete intent\n' > "$T/SSOT/tech-debt/README.md"
{
  printf -- '---\nid: DEBT-0003\nstatus: active\npriority: medium\nowner: SSOT/tech-debt/0003-visible.md\nclosure_condition: "tests/frontend-lint passes in CI"\nrevisit_signal: "path-glob:frontend/**"\nverification_guard: "npm run lint"\n---\n# Visible deferral\n\nHandle this later only when the frontend lint CI gate is touched.\n'
  printf '\n## Agent quick entry\n\nTrigger: frontend lint CI changes. First check: `npm run lint`. Do not close without CI evidence.\n'
} > "$T/SSOT/tech-debt/0003-visible.md"
out=$(run "$T"); code=$?
assert_exit "owner-backed deferral exits 0" "$code" "0"
assert_not_contains "owner-backed deferral has no SILENT-DEFERRAL fail" "$out" "[FAIL] [SILENT-DEFERRAL]"
rm -rf "$T"

echo ""
echo "===== summary: PASS=$PASS FAIL=$FAIL ====="
[[ "$FAIL" -eq 0 ]] && exit 0 || exit 1
